WITH cte AS (
  SELECT BRAND_CODE, SUM(TOTAL_FINAL_PRICE) as sum_spent
  FROM receipt_items
  WHERE strftime('%m', MODIFY_DATE) = '06' AND BRAND_CODE IS NOT NULL
  GROUP BY BRAND_CODE
  ORDER BY sum_spent DESC
)
SELECT NAME, sum_spent
FROM brands b
JOIN cte
ON b.BRAND_CODE = cte.BRAND_CODE
ORDER By sum_spent DESC
LIMIT 1;


SELECT BRAND_CODE
FROM receipt_items
WHERE strftime('%m', MODIFY_DATE) = '06' AND BRAND_CODE IS NOT NULL
GROUP BY BRAND_CODE
ORDER BY SUM(TOTAL_FINAL_PRICE) DESC
LIMIT 1;